name: Build Containers On Chart Release

on:
  push:
    branches: ["**"]

jobs:
  cas-nginx-sidecar-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: cas-nginx
          image_tag: latest,${{ github.sha }}
          dockerfile: nginx-sidecar/Dockerfile
          context: nginx-sidecar
