name: Release @bcgov-cas packages with lerna monorepo
on:
  release:
    types: [created]
  push:
    branches: ["feat/sso-react"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: yarn.lock
          scope: "bcgov-cas"
      - name: Install package dependencies
        run: yarn
      - name: Use Lerna to publish packages
        run: yarn lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
