name: Release '@bcgov/sso-express' on NPM
on:
  release:
    types: [created]
  push:
    branches:
      - feat/sso-express
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: packages/sso-express/yarn.lock
      - name: Install package dependencies
        run: yarn install --cwd packages/sso-express
      - name: Publish to NPM
        run: yarn publish --cwd packages/sso-express
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
