name: Test '@bcgov-cas/sso-express' package
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
          cache: "yarn"
          cache-dependency-path: packages/sso-express/yarn.lock
          scope: "bcgov-cas"
      - name: Install package dependencies
        run: yarn --cwd packages/sso-express
      - name: Run tests
        run: yarn --cwd packages/sso-express test
